export TERM=xterm-256color
export DISABLE_AUTO_TITLE=true
export CLICOLOR=true
export LS_COLORS="di=38;5;222:fi=38;5;59:ln=38;5;116:ex=38;5;107:ow=48;5;33;38;5;230:tw=48;5;235;38;5;33"
export LSCOLORS='exfxcxdxbxegedabagacad'

[[ -n "$TMUX" ]] && export TERM=screen-256color

setopt HIST_IGNORE_SPACE
unsetopt correctall
unsetopt correct

# Aliases
alias sz='source ~/.zshrc'
alias ez='vim ~/.zshrc'
alias rf='rm -Rf'
alias lh='ls -lAd .*'
alias gst='git status -sb'
alias ta='tmux attach-session -t '
alias tn='tmux new-session -s '
alias tl='tmux list-sessions'

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Ctrl-Esc-S to insert sudo at the start of line.
insert_sudo () { zle beginning-of-line; zle -U "sudo "; }
zle -N insert-sudo insert_sudo
bindkey "^[s" insert-sudo

# Ctrl-Esc-D to insert current date at cursor.
insert-datestamp() { LBUFFER+=${(%):-'%D{%Y-%m-%d}'}; }
zle -N insert-datestamp
bindkey '^[d' insert-datestamp
# Ctrl-Esc-Space to insert double space prefix at the start of line.
insert_space() { zle beginning-of-line; zle -U "  "; }
zle -N insert-space insert_space
bindkey "^[ " insert-space

## Google Specific
if [[ "$HOST" =~ "corp.google.com" && -e "$HOME/.zshrc.google" ]]; then
  source "$HOME/.zshrc.google"
fi
