export TERM=xterm-256color
[[ -n "$TMUX" ]] && export TERM=screen-256color

source `brew --prefix`/etc/profile.d/z.sh
[[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]] && source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
unsetopt correct_all
unsetopt correct

alias rf='rm -Rf'
alias lh='ls -lAd .*'
alias sz='source ~/.zshrc'
alias ez='vim ~/.zshrc'
alias gst='git status -sb'
alias ta='tmux attach-session -t '
alias tn='tmux new-session -s '
export DISABLE_AUTO_TITLE="true"
export CLICOLOR=true
export LS_COLORS="di=38;5;222:fi=38;5;59:ln=38;5;116:ex=38;5;107:ow=48;5;33;38;5;230:tw=48;5;235;38;5;33"
export LSCOLORS='exfxcxdxbxegedabagacad'

# Ctrl-Esc-S to insert sudo at the start of line.
insert_sudo () { zle beginning-of-line; zle -U "sudo "; }
zle -N insert-sudo insert_sudo
bindkey "^[s" insert-sudo

# Ctrl-Esc-D to insert current date at cursor.
insert-datestamp() { LBUFFER+=${(%):-'%D{%Y-%m-%d}'}; }
zle -N insert-datestamp
bindkey '^[d' insert-datestamp

# Ctrl-Esc-Space to insert double space prefix at the start of line.
insert_space() { zle beginning-of-line; zle -U "  "; }
zle -N insert-space insert_space
bindkey "^[ " insert-space

export PATH=$PATH:$HOME/bin

## Google Specific
if [[ "$HOST" =~ "corp.google.com" && -e "$HOME/.zshrc.google" ]]; then
  source "$HOME/.zshrc.google"
fi
